### ISSUE TITLE
Implement Delete Order Method

### ISSUE THREAD

**Issue by Naomimmm** [SpilledCofee/DataBase#57]

**Comment by jcasta30** [comment]
Coded and Implemented the Delete Order Method.  This method looks at the customer orders file and deletes a specific order based on the user's inputs. Everything seems to be running well. Made a pull request and awaiting approval from two reviewers.

**Comment by jcasta30** [comment]
Fututre implementations:
Further validation/error checking of invalid entries from users.

**Comment by jcasta30** [comment]
Implemented a few further error-checking/validation
